version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'foobar'
      MYSQL_USER: 'alan'
      MYSQL_PASSWORD: 'turing'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'foobar'
      POSTGRES_USER: 'alan'
      POSTGRES_PASSWORD: 'turing'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'foobar'
      MYSQL_USER: 'alan'
      MYSQL_PASSWORD: 'turing'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3307:3306'
    volumes:
      - mariadb-data:/var/lib/mysql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'secret'
    ports:
      - '1433:1433'
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mysql-data:
  postgres-data:
  mariadb-data:
  mssql-data:
