services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'foobar'
      MYSQL_USER: 'alan'
      MYSQL_PASSWORD: 'turing'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'foobar'
      POSTGRES_USER: 'alan'
      POSTGRES_PASSWORD: 'turing'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mysql-data:
  postgres-data:
