services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'foobar'
      MYSQL_USER: 'alan'
      MYSQL_PASSWORD: 'turing'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
